name: Contracts

on: [push, pull_request]

permissions: read-all

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.6.5"

      - name: Scarb version
        run: scarb --version

      - name: Check cairo format
        run: scarb fmt --check

      - name: Build cairo programs
        run: scarb build

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.6.5"

      - name: Scarb version
        run: scarb --version

      - name: Set up SNForge
        uses: foundry-rs/setup-snfoundry@v3

      - name: Run cairo tests
        run: snforge test
